package actually.portals.ActuallySize.world.grid.construction.rect;

import net.minecraft.world.phys.Vec2;
import net.minecraft.world.phys.Vec3;
import org.jetbrains.annotations.NotNull;

import java.util.ArrayList;

/**
 * A grid constructor that fills a single block
 * and ends any recursion chain
 *
 * @since 1.0.0
 * @author Actually Portals
 */
public class ASIGRSingle extends ASIGRectConstructor {

    /**
     * @param s      The scale of the grid, presumably the ceil of the
     *               player's scale who is building this so that it
     *               is a non-zero natural number.
     * @param x      If this rect spans the x-direction
     * @param y      If this rect spans the y-direction
     *
     * @param normal The normal to the local origin grid plane
     * @param offset A shift to the points generated by this rect, in rect coordinates
     * @param origin A shift to the points generated by this rect, in world coordinates
     *
     * @author Actually Portals
     * @since 1.0.0
     */
    public ASIGRSingle(int s, boolean x, boolean y, int normal, @NotNull Vec2 offset, @NotNull Vec3 origin) {
        super(s, x, y, normal, offset, origin);
    }

    /**
     * @since 1.0.0
     * @author Actually Portals
     */
    @Override
    public @NotNull ArrayList<Vec3> elaborate(int depth, int limit) {

        // Begin filling of vectors
        ArrayList<Vec3> ret = new ArrayList<>();
        if (limit == 0) { return ret; }

        // Include my single point, but only at depth 0
        if (depth == 0) { ret.add(cook(0, 0)); }

        // Done
        return ret;
    }
}
