package actually.portals.ActuallySize.world.grid.construction.rect;


import actually.portals.ActuallySize.world.grid.construction.ASIGConstructor;
import gunging.ootilities.GungingOotilitiesMod.ootilityception.OotilityNumbers;
import net.minecraft.world.phys.Vec2;
import net.minecraft.world.phys.Vec3;
import org.jetbrains.annotations.NotNull;

/**
 * A grid constructor that fills a two-dimensional volume of blocks.
 *
 * @since 1.0.0
 * @author Actually Portals
 */
public abstract class ASIGRectConstructor implements ASIGConstructor {

    /**
     * If this plane is parallel to the x-axis
     *
     * @since 1.0.0
     */
    private final boolean x;

    /**
     * If this plane is parallel to the y-axis
     *
     * @since 1.0.0
     */
    private final boolean y;

    /**
     * If this plane is parallel to the z-axis
     *
     * @since 1.0.0
     */
    private final boolean z;

    /**
     * How many blocks detached from the local origin grid plane
     *
     * @since 1.0.0
     */
    private final int normal;

    /**
     * The scale of the grid, presumably the ceil of the
     * player's scale who is building this so that it
     * is a non-zero natural number.
     *
     * @since 1.0.0
     */
    private final int s;

    /**
     * A shift to the locations elaborated
     * by this rect constructor, in the
     * coordinates of this plane
     *
     * @since 1.0.0
     */
    @NotNull private final Vec2 offset;

    /**
     * A shift to the locations elaborated
     * by this rect constructor, in the
     * absolute world coordinates
     *
     * @since 1.0.0
     */
    @NotNull private final Vec3 origin;

    /**
     * If both x and y params are set to false, x is forced to true
     * so that the plane of choosing is the X-Z plane
     *
     * @param s The scale of the grid, presumably the ceil of the
     *          player's scale who is building this so that it
     *          is a non-zero natural number.
     *
     * @param x If this rect spans the x-direction
     * @param y If this rect spans the y-direction
     *
     * @param normal The normal to the local origin grid plane
     * @param offset A shift to the points generated by this rect, in rect coordinates
     * @param origin A shift to the points generated by this rect, in world coordinates
     *
     * @since 1.0.0
     * @author Actually Portals
     */
    public ASIGRectConstructor(int s, boolean x, boolean y, int normal, @NotNull Vec2 offset, @NotNull Vec3 origin) {
        this.s = s;
        this.offset = offset;
        this.x = x || !y;
        this.y = y;
        this.z = !x || !y;
        this.normal = normal;
        this.origin = origin;
    }

    /**
     * @since 1.0.0
     * @author Actually Portals
     */
    @Override public int getGridScale() { return s; }

    /**
     * If this plane is parallel to the X-Y plane, perpendicular to the Z-axis
     *
     * @since 1.0.0
     * @author Actually Portals
     */
    public boolean isXY() { return x && y; }

    /**
     * If this plane is parallel to the Y-Z plane, perpendicular to the X-axis
     *
     * @since 1.0.0
     * @author Actually Portals
     */
    public boolean isYZ() { return y && z; }

    /**
     * If this plane is parallel to the Z-X plane, perpendicular to the Y-axis
     *
     * @since 1.0.0
     * @author Actually Portals
     */
    public boolean isZX() { return z && x; }

    /**
     * How many blocks detached from the local origin grid plane.
     * <br><br>
     * That is, the very first plane that could possibly fit
     * in this grid chunk.
     *
     * @since 1.0.0
     * @author Actually Portals
     */
    public int getNormal() { return normal; }

    /**
     * @since 1.0.0
     * @author Actually Portals
     */
    public @NotNull Vec2 getOffset() { return offset; }

    /**
     * @since 1.0.0
     * @author Actually Portals
     */
    public @NotNull Vec3 getOrigin() { return origin; }

    /**
     * @param i One dimension along this rect
     * @param j The other dimension along this rect
     *
     * @since 1.0.0
     * @author Actually Portals
     */
    @NotNull public Vec3 cook(int i, int j) {

        // Shorthand origin
        int io = OotilityNumbers.round(getOffset().x);
        int jo = OotilityNumbers.round(getOffset().y);

        int ix = OotilityNumbers.round(getOrigin().x);
        int iy = OotilityNumbers.round(getOrigin().y);
        int iz = OotilityNumbers.round(getOrigin().z);

        // Essentially transforms it to X,Y,Z
        if (isXY()) { return new Vec3(i + io + ix, j + jo + iy, getNormal() + iz); }
        if (isYZ()) { return new Vec3(getNormal() + ix, j + jo + iy, i + io + iz); }
        if (isZX()) { return new Vec3(i + io + ix, getNormal() + iy, j + jo + iz); }

        // Defaults to ZX I guess, but this should never happen
        return new Vec3(i + io + ix, getNormal() + iy, j + jo + iz);
    }

    /**
     * @param S Grid size you are looking for
     *
     * @param i The shift in origin for this child rect
     *          relative to the origin of this parent one
     *
     * @param j The shift in origin for this child rect
     *          relative to the origin of this parent one
     *
     * @return The appropriate Rect Constructor for this size
     *
     * @since 1.0.0
     * @author Actually Portals
     */
    @NotNull public ASIGRectConstructor toSize(int S, int i, int j) {

        // Shorthand origin
        int io = OotilityNumbers.round(getOffset().x);
        int jo = OotilityNumbers.round(getOffset().y);
        Vec2 pos = new Vec2(io + i, jo + j);

        // Choose appropriate rect
        if (S == 1) { return new ASIGRSingle(S, x, y, getNormal(), pos, getOrigin()); }
        if (S == 2) { return new ASIGRDouble(S, x, y, getNormal(), pos, getOrigin()); }

        // Even or odd constructor
        boolean isEven = (S % 2 == 0);
        return isEven ?
                new ASIGREven(S, x, y, getNormal(), pos, getOrigin()) :
                new ASIGROdd(S, x, y, getNormal(), pos, getOrigin());
    }

    /**
     * @param S The scale of this grid
     *
     * @param x If this rect spans the x-direction
     * @param y If this rect spans the y-direction
     *
     * @param i Actual shift of this rect
     * @param j Actual shift of this rect
     *
     * @param normal The normal to the local origin grid plane
     * @param origin A shift to the points generated by this rect, in world coordinates
     *
     * @return The appropriate Rect Constructor for this size
     *
     * @since 1.0.0
     * @author Actually Portals
     */
    @NotNull public static ASIGRectConstructor forSize(int S, boolean x, boolean y, int i, int j, int normal, @NotNull Vec3 origin) {

        // Delegate to the rect get-for-size method
        return new ASIGRSingle(1, x, y, normal, Vec2.ZERO, origin).toSize(S, i, j);
    }
}
