package actually.portals.ActuallySize.world.grid.construction.cube;

import actually.portals.ActuallySize.world.grid.construction.ASIGConstructor;
import gunging.ootilities.GungingOotilitiesMod.ootilityception.OotilityNumbers;
import net.minecraft.world.phys.Vec2;
import net.minecraft.world.phys.Vec3;
import org.jetbrains.annotations.NotNull;

/**
 * A grid constructor that fills a three-dimensional volume of blocks.
 *
 * @since 1.0.0
 * @author Actually Portals
 */
public abstract class ASIGCubeConstructor implements ASIGConstructor {

    /**
     * The scale of the grid, presumably the ceil of the
     * player's scale who is building this so that it
     * is a non-zero natural number.
     *
     * @since 1.0.0
     */
    private final int s;

    /**
     * A shift to the locations elaborated
     * by this rect constructor
     *
     * @since 1.0.0
     */
    @NotNull private final Vec3 origin;

    /**
     * @param s The scale of the grid, presumably the ceil of the
     *          player's scale who is building this so that it
     *          is a non-zero natural number.
     *
     * @param origin A shift to the points generated by this rect
     *
     * @since 1.0.0
     * @author Actually Portals
     */
    public ASIGCubeConstructor(int s, @NotNull Vec3 origin) {
        this.s = s;
        this.origin = origin;
    }

    /**
     * @since 1.0.0
     * @author Actually Portals
     */
    @Override public int getGridScale() { return s; }

    /**
     * @since 1.0.0
     * @author Actually Portals
     */
    public @NotNull Vec3 getOrigin() { return origin; }

    /**
     * @param i One dimension along this rect
     * @param j The other dimension along this rect
     *
     * @since 1.0.0
     * @author Actually Portals
     */
    @NotNull public Vec3 cook(int i, int j, int k) {

        // Shorthand origin
        int io = OotilityNumbers.round(getOrigin().x);
        int jo = OotilityNumbers.round(getOrigin().y);
        int ko = OotilityNumbers.round(getOrigin().z);

        // Cook point
        return new Vec3(i + io, j + jo, k + ko);
    }
}
